// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyryrdazzekirwtxztva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5cnlyZGF6emVraXJ3dHh6dHZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDU5MDYsImV4cCI6MjA3MzA4MTkwNn0.XVupEzhtLwNRr5OJ5b-aReBC_FdJ4YIsr1PQnVyN7DU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});